"""Render a parsed Benchmark into checklist outputs: Markdown, JSON, CSV."""

from __future__ import annotations

import csv
import io
import json


def to_json(benchmark) -> str:
    return json.dumps(benchmark.to_dict(), indent=2, ensure_ascii=False)


CSV_FIELDS = [
    "stig_id", "group_id", "severity", "cat", "title",
    "status", "ai_triage", "ai_automation", "ai_summary",
]


def to_csv(benchmark) -> str:
    buf = io.StringIO()
    writer = csv.DictWriter(buf, fieldnames=CSV_FIELDS)
    writer.writeheader()
    for r in benchmark.rules:
        writer.writerow({
            "stig_id": r.stig_id,
            "group_id": r.group_id,
            "severity": r.severity,
            "cat": r.cat,
            "title": r.title,
            "status": "not_reviewed",
            "ai_triage": r.ai.get("triage", ""),
            "ai_automation": r.ai.get("automation", ""),
            "ai_summary": r.ai.get("summary", ""),
        })
    return buf.getvalue()


def _md_escape(text: str) -> str:
    return text.replace("|", "\\|")


def to_markdown(benchmark) -> str:
    b = benchmark
    counts = {"high": 0, "medium": 0, "low": 0}
    for r in b.rules:
        counts[r.severity] = counts.get(r.severity, 0) + 1

    lines = []
    lines.append(f"# STIG Checklist — {b.title}")
    lines.append("")
    meta = f"**Version:** {b.version}"
    if b.release_info:
        meta += f" · {b.release_info}"
    meta += f" · **Source:** `{b.source_file}`"
    lines.append(meta)
    lines.append("")
    lines.append(
        f"**{len(b.rules)} rules** — "
        f"{counts.get('high', 0)} CAT I (high) · "
        f"{counts.get('medium', 0)} CAT II (medium) · "
        f"{counts.get('low', 0)} CAT III (low)"
    )
    lines.append("")

    has_ai = any(r.ai for r in b.rules)
    if has_ai:
        lines.append("## Triage overview (AI-assisted)")
        lines.append("")
        lines.append("| STIG ID | CAT | Triage | Automatable | Rule |")
        lines.append("|---|---|---|---|---|")
        for r in b.rules:
            lines.append(
                f"| {r.stig_id} | {r.cat} | {r.ai.get('triage', '—')} "
                f"| {r.ai.get('automation', '—')} | {_md_escape(r.title)} |"
            )
        lines.append("")

    sev_titles = [
        ("high", "CAT I — High severity"),
        ("medium", "CAT II — Medium severity"),
        ("low", "CAT III — Low severity"),
    ]
    for sev, heading in sev_titles:
        rules = [r for r in b.rules if r.severity == sev]
        if not rules:
            continue
        lines.append(f"## {heading} ({len(rules)} rules)")
        lines.append("")
        for r in rules:
            lines.append(f"### ☐ {r.stig_id} — {r.title}")
            lines.append("")
            lines.append(f"*{r.group_id} · {r.rule_id} · {r.cat}*")
            lines.append("")
            if r.ai:
                lines.append(f"> **What this means:** {r.ai.get('summary', '')}")
                if r.ai.get("caution"):
                    lines.append(">")
                    lines.append(f"> **Caution:** {r.ai['caution']}")
                lines.append("")
            if r.discussion:
                lines.append("<details><summary>Why it matters (STIG discussion)</summary>")
                lines.append("")
                lines.append(r.discussion)
                lines.append("")
                lines.append("</details>")
                lines.append("")
            if r.check_text:
                lines.append("**Check:**")
                lines.append("")
                lines.append("```")
                lines.append(r.check_text)
                lines.append("```")
                lines.append("")
            if r.fix_text:
                lines.append("**Fix:**")
                lines.append("")
                lines.append("```")
                lines.append(r.fix_text)
                lines.append("```")
                lines.append("")
            if r.ccis:
                lines.append(f"*CCIs: {', '.join(r.ccis)}*")
                lines.append("")
    lines.append("---")
    lines.append(
        "*Generated by [stig-prep](https://github.com/) — module 1 of an "
        "AI-assisted STIG compliance pipeline. Always validate against the "
        "official DISA STIG before relying on this checklist.*"
    )
    return "\n".join(lines)
