"""POA&M outputs: JSON for the next tool, Markdown and CSV for the person."""

from __future__ import annotations

import csv
import io
import json

from .poam import CLOSED, KIND_FINDING, PoamPack

_CAT = {"high": "CAT I", "medium": "CAT II", "low": "CAT III"}


def to_json(pack: PoamPack) -> str:
    body = {
        "pack_format": pack.pack_format,
        "pack_id": pack.pack_id,
        "stig_title": pack.stig_title,
        "stig_version": pack.stig_version,
        "source_scan": pack.source_scan,
        "created": pack.created,
        "notes": pack.notes,
        "platform": pack.platform,
        "summary": pack.summary(),
        "entries": [
            {
                **{k: getattr(e, k) for k in e.__dataclass_fields__},
                "digest": e.digest(),
                "drifted": e.is_drifted(),
            }
            for e in pack.entries
        ],
    }
    return json.dumps(body, indent=2) + "\n"


def to_markdown(pack: PoamPack) -> str:
    s = pack.summary()
    L: list[str] = []
    L.append(f"# STIG POA&M drafts — {pack.stig_title or pack.pack_id}")
    L.append("")
    L.append(f"- **Pack:** `{pack.pack_id}` ({pack.stig_version})")
    L.append(f"- **Source scan:** `{pack.source_scan}`")
    if pack.platform:
        L.append(f"- **Platform:** {pack.platform}")
    L.append(f"- **Created:** {pack.created}")
    L.append("")
    L.append("## Coverage of this draft")
    L.append("")
    L.append(
        f"**{s['findings']} finding(s)** drafted from scan failures. "
        f"{s['evaluation_gaps']} evaluation gap(s) and {s['manual']} manual "
        f"inspection item(s) are listed separately. "
        f"**{s['closed']} closed.** Closing is a named person's act; this "
        "module never marks an item complete on its own."
    )
    L.append("")
    if s["untrusted"]:
        L.append(
            f"> **WARNING — {s['untrusted']} untrusted draft(s).** The "
            "underlying scan result came from a check no person approved. "
            "Do not use those rows as accreditation evidence."
        )
        L.append("")
    if s["drifted"]:
        L.append(
            f"> **DRIFTED — {s['drifted']} approved draft(s) were edited "
            "after approval.** Re-review them before closing."
        )
        L.append("")

    L.append("| Status | Review | Severity | STIG ID | Weakness |")
    L.append("|---|---|---|---|---|")
    for e in sorted(
        pack.entries,
        key=lambda x: (
            0 if x.kind == KIND_FINDING else 1,
            {"high": 0, "medium": 1, "low": 2}.get(x.severity, 9),
            x.stig_id,
        ),
    ):
        flag = "" if e.trusted else " ⚠︎"
        drift = " [DRIFTED]" if e.is_drifted() else ""
        L.append(
            f"| {e.poam_status}{flag} | {e.review_status}{drift} | "
            f"{_CAT.get(e.severity, e.severity)} | `{e.stig_id}` | "
            f"{_cell(e.weakness)} |"
        )
    L.append("")

    findings = [e for e in pack.entries if e.kind == KIND_FINDING]
    if findings:
        L.append("## Findings")
        L.append("")
        for e in findings:
            L.extend(_entry_md(e))

    gaps = [e for e in pack.entries if e.kind != KIND_FINDING]
    if gaps:
        L.append("## Evidence gaps (not findings)")
        L.append("")
        L.append(
            "These rows are here so a coverage gap is visible. They are not "
            "failures and must not be counted as either compliant or non-compliant."
        )
        L.append("")
        for e in gaps:
            L.extend(_entry_md(e))

    L.append("---")
    L.append("")
    L.append(
        "Generated by `stig-assess`, module 3 of stig-ai-pipeline. Drafts "
        "are unreviewed until a named person approves them. The module never "
        "closes a finding and never applies a change to a system. "
        "Authoritative requirements are the DISA STIG text, not this draft."
    )
    L.append("")
    return "\n".join(L)


def to_csv(pack: PoamPack) -> str:
    fields = [
        "stig_id", "group_id", "severity", "cat", "kind", "poam_status",
        "review_status", "trusted", "weakness", "description",
        "recommendation", "impact", "resources", "scheduled_completion",
        "triage", "caution", "finding_status", "closure_kind",
        "closed_by", "reviewed_by",
    ]
    buf = io.StringIO()
    writer = csv.DictWriter(buf, fieldnames=fields)
    writer.writeheader()
    for e in pack.entries:
        writer.writerow({
            "stig_id": e.stig_id,
            "group_id": e.group_id,
            "severity": e.severity,
            "cat": _CAT.get(e.severity, e.severity),
            "kind": e.kind,
            "poam_status": e.poam_status,
            "review_status": e.review_status,
            "trusted": "yes" if e.trusted else "no",
            "weakness": e.weakness,
            "description": e.description,
            "recommendation": e.recommendation,
            "impact": e.impact,
            "resources": e.resources,
            "scheduled_completion": e.scheduled_completion,
            "triage": e.triage,
            "caution": e.caution,
            "finding_status": e.finding_status,
            "closure_kind": e.closure_kind,
            "closed_by": e.closed_by or "",
            "reviewed_by": e.reviewed_by or "",
        })
    return buf.getvalue()


def _entry_md(e) -> list[str]:
    L = [
        f"### {e.stig_id} — {e.weakness}",
        "",
        f"- **Severity:** {_CAT.get(e.severity, e.severity)}",
        f"- **Kind:** {e.kind}",
        f"- **POA&M status:** {e.poam_status}"
        + (f" ({e.closure_kind} by {e.closed_by})" if e.poam_status == CLOSED else ""),
        f"- **Review:** {e.review_status}"
        + (f" by {e.reviewed_by}" if e.reviewed_by else ""),
    ]
    if e.triage:
        L.append(f"- **Triage:** {e.triage}")
    if not e.trusted:
        L.append("- **Trusted:** no — underlying check was unreviewed")
    L.append("")
    L.append(e.description)
    L.append("")
    L.append(f"**Recommendation.** {e.recommendation}")
    L.append("")
    L.append(f"**Impact.** {e.impact}")
    L.append("")
    L.append(f"**Resources.** {e.resources}")
    if e.scheduled_completion:
        L.append("")
        L.append(f"**Scheduled completion.** {e.scheduled_completion}")
    L.append("")
    return L


def _cell(text: str) -> str:
    text = (text or "").replace("|", "/").replace("\n", " ")
    return (text[:90] + "…") if len(text) > 90 else text
