"""PDF scan reports. Standard library only — no extra dependency.

A compliance report that only exists as Markdown is easy to lose in a
folder of checklists. The PDF is the same evidence: coverage first, then
counts, then every result. It is generated on the machine that ran the
scan. Nothing here reaches a network.
"""

from __future__ import annotations

from .evaluate import PASS, FAIL, ERROR, MANUAL, SKIPPED
from .scan import ScanReport, SEVERITY_LABEL
from .summary import (
    breakdown_rows, coverage_rows, severity_rows, summarize_report,
)

PAGE_W = 612
PAGE_H = 792
MARGIN = 50
BOTTOM = 56

_STATUS = {
    PASS: "PASS",
    FAIL: "FAIL",
    ERROR: "ERROR",
    MANUAL: "MANUAL",
    SKIPPED: "SKIP",
}


def to_pdf(report: ScanReport) -> bytes:
    """Render *report* as a PDF 1.4 document (bytes)."""
    lines = _layout(report)
    pages = _paginate(lines)
    return _assemble(pages)


# -------------------------------------------------------------- layout ----

def _layout(report: ScanReport) -> list[tuple]:
    """Styled lines: (kind, text) where kind is title|h1|h2|body|meta|warn|row."""
    c = report.counts()
    evaluated = c[PASS] + c[FAIL]
    total = len(report.results)
    pct = (evaluated / total * 100) if total else 0.0
    untrusted = [r for r in report.results if not r.trusted and r.status in (PASS, FAIL)]
    host = report.host or {}
    host_line = (
        f"{host.get('hostname', '?')}  "
        f"({host.get('system', '?')} {host.get('macos_version') or host.get('release', '')})"
    )

    out: list[tuple] = []
    out.append(("title", f"STIG scan report — {report.stig_title or report.pack_id}"))
    out.append(("meta", f"Check pack: {report.pack_id}  ({report.stig_version})"))
    out.append(("meta", f"Host: {host_line}"))
    out.append(("meta", f"Run: {report.started} → {report.finished}  ·  "
                        f"source: {report.options.get('runner')}"))
    out.append(("gap", ""))

    out.append(("h1", "Coverage"))
    out.append(("body",
                f"{evaluated} of {total} rules ({pct:.1f}%) were actually evaluated "
                "on this host. The remaining results produced no compliance evidence "
                "and must not be counted as either compliant or non-compliant."))
    out.append(("body",
                f"Pass {c[PASS]}   Fail {c[FAIL]}   Error {c[ERROR]}   "
                f"Manual {c[MANUAL]}   Skipped {c[SKIPPED]}   Total {total}"))
    out.append(("gap", ""))

    story = summarize_report(report)
    out.append(("h1", "What this means"))
    out.append(("body", story.headline))
    out.append(("body", story.meaning))
    out.append(("body", story.next_step))
    out.append(("gap", ""))
    out.append(("h2", "How the numbers break down"))
    for label, bar, caption in breakdown_rows(story):
        out.append(("row", f"{label:<22} {bar}  {caption}"))
    out.append(("meta", story.judged_line))
    if any(story.fails_by_severity.values()):
        out.append(("gap", ""))
        out.append(("h2", "Fails by severity"))
        for label, bar, caption in severity_rows(story):
            out.append(("row", f"{label:<22} {bar}  {caption}"))
    out.append(("gap", ""))
    out.append(("h2", "Coverage"))
    for label, bar, caption in coverage_rows(story):
        out.append(("row", f"{label:<22} {bar}  {caption}"))
    out.append(("gap", ""))

    if untrusted:
        out.append(("warn",
                    f"WARNING — {len(untrusted)} result(s) came from checks that no "
                    "human has approved (--include-unreviewed). They are not "
                    "admissible as compliance evidence."))
        out.append(("gap", ""))

    cat1 = report.cat1_failures()
    if cat1:
        out.append(("h1", f"CAT I failures ({len(cat1)})"))
        for r in cat1:
            out.append(("body", f"{r.stig_id}  {r.title}"))
            if r.detail:
                out.append(("meta", r.detail))
        out.append(("gap", ""))

    out.append(("h1", "Results"))
    out.append(("row", "STATUS    SEV     STIG ID              REQUIREMENT"))
    order = {FAIL: 0, ERROR: 1, MANUAL: 2, PASS: 3, SKIPPED: 4}
    sev_order = {"high": 0, "medium": 1, "low": 2}
    for r in sorted(report.results,
                    key=lambda x: (order.get(x.status, 9),
                                   sev_order.get(x.severity, 9), x.stig_id)):
        flag = "" if r.trusted else " !"
        title = r.title if len(r.title) <= 70 else r.title[:69] + "…"
        out.append(("row",
                    f"{_STATUS.get(r.status, r.status):<8}{flag:<2}"
                    f"{SEVERITY_LABEL.get(r.severity, r.severity):<8}"
                    f"{r.stig_id:<20}{title}"))
        if r.detail:
            out.append(("meta", f"          {r.detail}"))

    out.append(("gap", ""))
    out.append(("meta",
                "Generated by stig-scan on the machine that was scanned. "
                "Check commands are human-approved and content-frozen; the "
                "scanner executes no unapproved code and makes no configuration "
                "changes. Authoritative requirements are the DISA STIG text, "
                "not this report."))
    return out


def _paginate(lines: list[tuple]) -> list[list[tuple]]:
    """Split styled lines into pages, wrapping long body text."""
    pages: list[list[tuple]] = []
    current: list[tuple] = []
    y = PAGE_H - MARGIN

    def height(kind: str) -> int:
        return {"title": 22, "h1": 20, "h2": 16, "gap": 10,
                "warn": 28, "body": 14, "meta": 12, "row": 12}.get(kind, 14)

    def wrap_width(kind: str) -> int:
        return {"title": 78, "h1": 86, "warn": 86, "body": 92,
                "meta": 96, "row": 102}.get(kind, 92)

    def flush():
        nonlocal current, y
        if current:
            pages.append(current)
        current = []
        y = PAGE_H - MARGIN

    for kind, text in lines:
        wrapped = _wrap(text, wrap_width(kind)) if kind not in ("gap",) else [""]
        need = height(kind) + max(0, len(wrapped) - 1) * 12
        if y - need < BOTTOM:
            flush()
        if kind == "title" and pages:
            # titles only belong on page 1; treat overflow as h1
            kind = "h1"
        for i, piece in enumerate(wrapped):
            current.append((kind if i == 0 else ("meta" if kind == "warn" else kind), piece))
            y -= height(kind) if i == 0 else 12
    flush()
    return pages or [[]]


def _wrap(text: str, width: int) -> list[str]:
    if not text:
        return [""]
    words = text.split()
    if not words:
        return [""]
    lines: list[str] = []
    cur = words[0]
    for w in words[1:]:
        trial = f"{cur} {w}"
        if len(trial) > width:
            lines.append(cur)
            cur = w
        else:
            cur = trial
    lines.append(cur)
    return lines


# --------------------------------------------------------------- write ----

def _assemble(pages: list[list[tuple]]) -> bytes:
    font_reg = _obj(b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>")
    font_bold = _obj(b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>")
    contents = []
    page_objs = []
    for i, page in enumerate(pages, start=1):
        stream = _page_stream(page, i, len(pages))
        contents.append(_stream(stream))
        page_objs.append(None)  # filled after we know object numbers

    # Object numbers: 1 Catalog, 2 Pages, fonts, then per-page content + page
    # We assign them by building a list in order.
    objects: list[bytes] = [b""]  # 1-indexed
    objects.append(b"")  # 1 catalog — patched
    objects.append(b"")  # 2 pages — patched
    objects.append(font_reg)
    objects.append(font_bold)

    page_nums = []
    for stream_body in contents:
        objects.append(stream_body)
        content_n = len(objects) - 1
        page_body = (
            b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] "
            b"/Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> "
            + f"/Contents {content_n} 0 R >>".encode()
        )
        objects.append(page_body)
        page_nums.append(len(objects) - 1)

    kids = " ".join(f"{n} 0 R" for n in page_nums)
    objects[2] = f"<< /Type /Pages /Kids [{kids}] /Count {len(page_nums)} >>".encode()
    objects[1] = b"<< /Type /Catalog /Pages 2 0 R >>"

    out = bytearray(b"%PDF-1.4\n%\xe2\xe3\xcf\xd3\n")
    offsets = [0]
    for n in range(1, len(objects)):
        offsets.append(len(out))
        out += f"{n} 0 obj\n".encode() + objects[n] + b"\nendobj\n"
    xref_pos = len(out)
    out += f"xref\n0 {len(objects)}\n".encode()
    out += b"0000000000 65535 f \n"
    for n in range(1, len(objects)):
        out += f"{offsets[n]:010d} 00000 n \n".encode()
    out += (
        f"trailer\n<< /Size {len(objects)} /Root 1 0 R >>\n"
        f"startxref\n{xref_pos}\n%%EOF\n"
    ).encode()
    return bytes(out)


def _obj(body: bytes) -> bytes:
    return body


def _stream(data: bytes) -> bytes:
    return f"<< /Length {len(data)} >>\nstream\n".encode() + data + b"\nendstream"


def _page_stream(lines: list[tuple], page_no: int, page_count: int) -> bytes:
    y = PAGE_H - MARGIN
    cmds = ["BT"]
    first = True

    def show(font: str, size: int, text: str, leading: int, color: str = "0 0 0"):
        nonlocal y, first
        esc = _pdf_escape(text)
        if first:
            cmds.append(f"/{font} {size} Tf")
            cmds.append(f"{color} rg")
            cmds.append(f"1 0 0 1 {MARGIN} {y} Tm")
            cmds.append(f"({esc}) Tj")
            first = False
        else:
            cmds.append(f"/{font} {size} Tf")
            cmds.append(f"{color} rg")
            cmds.append(f"0 -{leading} Td")
            cmds.append(f"({esc}) Tj")
        y -= leading

    navy = "0.086 0.141 0.231"
    muted = "0.37 0.43 0.50"
    red = "0.75 0.22 0.17"
    sizes = {"title": ("F2", 15, 20, navy), "h1": ("F2", 12, 18, navy),
             "h2": ("F2", 11, 16, navy), "body": ("F1", 10, 14, "0 0 0"),
             "meta": ("F1", 9, 12, muted), "warn": ("F2", 10, 14, red),
             "row": ("F1", 8, 11, "0 0 0"), "gap": ("F1", 8, 10, "0 0 0")}

    for kind, text in lines:
        font, size, leading, color = sizes[kind]
        if kind == "gap":
            if not first:
                cmds.append(f"0 -{leading} Td")
                y -= leading
            continue
        show(font, size, text, leading, color)

    # footer — reset position
    cmds.append("ET")
    footer = _pdf_escape(f"stig-ai-pipeline  ·  page {page_no} of {page_count}")
    cmds.append("BT")
    cmds.append("/F1 8 Tf")
    cmds.append(f"{muted} rg")
    cmds.append(f"1 0 0 1 {MARGIN} 36 Tm")
    cmds.append(f"({footer}) Tj")
    cmds.append("ET")
    return "\n".join(cmds).encode("latin-1", "replace")


def _pdf_escape(text: str) -> str:
    cleaned = text.replace("\u2014", "-").replace("\u2013", "-").replace("\u2026", "...")
    cleaned = cleaned.encode("latin-1", "replace").decode("latin-1")
    return cleaned.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")
