"""Remediation outputs: scripts for review, JSON / Markdown for the record."""

from __future__ import annotations

import json
from pathlib import Path

from .pack import MODE_SCRIPT, RemediationPack

_CAT = {"high": "CAT I", "medium": "CAT II", "low": "CAT III"}


def to_json(pack: RemediationPack) -> str:
    body = {
        "pack_format": pack.pack_format,
        "pack_id": pack.pack_id,
        "stig_title": pack.stig_title,
        "stig_version": pack.stig_version,
        "source_scan": pack.source_scan,
        "created": pack.created,
        "notes": pack.notes,
        "platform": pack.platform,
        "summary": pack.summary(),
        "remediations": [
            {
                **{k: getattr(r, k) for k in r.__dataclass_fields__},
                "digest": r.digest(),
                "drifted": r.is_drifted(),
            }
            for r in pack.remediations
        ],
    }
    return json.dumps(body, indent=2) + "\n"


def to_markdown(pack: RemediationPack) -> str:
    s = pack.summary()
    L = [
        f"# STIG remediation drafts — {pack.stig_title or pack.pack_id}",
        "",
        f"- **Pack:** `{pack.pack_id}` ({pack.stig_version})",
        f"- **Source scan:** `{pack.source_scan}`",
        f"- **Platform:** {pack.platform}",
        f"- **Created:** {pack.created}",
        "",
        f"**{s['script']} script draft(s)**, {s['manual']} manual, "
        f"{s['unsupported']} unsupported. **{s['approved']} approved. "
        f"{s['applied']} applied.** Approval does not apply a change. "
        "Apply defaults to dry-run and is refused in CI.",
        "",
    ]
    if s["drifted"]:
        L.append(
            f"> **DRIFTED — {s['drifted']} approved script(s) were edited "
            "after approval.** Re-review them before apply."
        )
        L.append("")
    L += [
        "| Review | Apply | Severity | STIG ID | Mode | Shape |",
        "|---|---|---|---|---|---|",
    ]
    for r in sorted(
        pack.remediations,
        key=lambda x: ({"high": 0, "medium": 1, "low": 2}.get(x.severity, 9), x.stig_id),
    ):
        drift = " [DRIFTED]" if r.is_drifted() else ""
        L.append(
            f"| {r.review_status}{drift} | {r.apply_status} | "
            f"{_CAT.get(r.severity, r.severity)} | `{r.stig_id}` | "
            f"{r.mode} | {r.shape or '—'} |"
        )
    L.append("")
    for r in pack.remediations:
        L += [
            f"### {r.stig_id} — {r.title}",
            "",
            f"- **Mode:** {r.mode} · **confidence:** {r.author_confidence} · "
            f"**shape:** {r.shape or 'none'}",
            f"- **Review:** {r.review_status}"
            + (f" by {r.reviewed_by}" if r.reviewed_by else ""),
            f"- **Apply:** {r.apply_status}",
            "",
            r.rationale,
            "",
        ]
        if r.script:
            fence = "powershell" if r.language == "powershell" else "bash"
            L += [f"```{fence}", r.script, "```", ""]
        if r.author_note:
            L += [f"*{r.author_note}*", ""]
    L += [
        "---",
        "",
        "Generated by `stig-harden`, module 4 of stig-ai-pipeline. "
        "Scripts are unreviewed until a named person approves them. "
        "The module never applies an unreviewed remediation and never "
        "applies in CI. Authoritative requirements are the DISA STIG text, "
        "not this draft.",
        "",
    ]
    return "\n".join(L)


def write_scripts(pack: RemediationPack, dest: Path) -> list[Path]:
    """Write one file per script draft. Does not execute anything."""
    dest.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for r in pack.remediations:
        if r.mode != MODE_SCRIPT or not r.script.strip():
            continue
        ext = ".ps1" if r.language == "powershell" else ".sh"
        path = dest / f"{r.stig_id}{ext}"
        header = (
            f"# {r.stig_id} — {r.title}\n"
            f"# DRAFT. Not applied. Digest {r.digest()}\n"
            f"# Review status: {r.review_status}\n"
        )
        path.write_text(header + r.script + "\n", encoding="utf-8")
        written.append(path)
    return written
